Update the cran submission workflow to handle env var names and values better

diff --git a/.github/workflows/submit-to-cran.yaml b/.github/workflows/submit-to-cran.yaml
--- a/.github/workflows/submit-to-cran.yaml
+++ b/.github/workflows/submit-to-cran.yaml
@@ -4,8 +4,8 @@ on:
   workflow_dispatch:
     inputs:
       PACKAGE_VERSION:
-        description: The version of the package to be submitted to CRAN
-        required: true
+        description: The version of the package to be submitted to CRAN. If not provided, use the latest version.
+        required: false
         type: string
 
 jobs:
@@ -20,10 +20,56 @@ jobs:
         env:
             GH_TOKEN: ${{ github.token }}
 
-  submitToCran:
+  determinePackageMetadata:
     runs-on: ubuntu-latest
     needs: validateActor
     if: ${{ needs.validateActor.outputs.CAN_SUBMIT_TO_CRAN == 'true' }}
+
+    outputs:
+      PACKAGE_VERSION: ${{ steps.getVersion.outputs.PACKAGE_VERSION }}
+      PKG_FILE_NAME: ${{ steps.getPackageName.outputs.PKG_FILE_NAME }}
+      TAG_NAME: ${{ steps.getVersion.outputs.TAG_NAME }}
+
+    steps:
+      - name: Determine package version
+        id: getVersion
+        run: |
+          if [ -z "${{ github.event.inputs.PACKAGE_VERSION }}" ]; then
+            # Get the latest tag and strip leading "v"
+            TAG_NAME=$(git describe --tags `git rev-list --tags --max-count=1`)
+            echo "No version input provided. Using latest tag: $TAG_NAME"
+
+            PACKAGE_VERSION="${TAG_NAME#v}"
+          else
+            PACKAGE_VERSION="${{ github.event.inputs.PACKAGE_VERSION }}"
+            echo "Using provided version: $PACKAGE_VERSION"
+            TAG_NAME="v${PACKAGE_VERSION}"
+
+            if git rev-parse "${TAG_NAME}" >/dev/null 2>&1; then
+              echo "Provided version exists in tags: ${TAG_NAME}"
+            else
+              echo "Error: Provided version does not exist in tags: ${TAG_NAME}"
+              exit 1
+            fi
+          fi
+
+          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> "$GITHUB_ENV"
+          echo "TAG_NAME"="$TAG_NAME" >> "$GITHUB_OUTPUT"
+
+      - name: Construct package local file name
+        id: getPackageName
+        run: |
+          echo "PKG_FILE_NAME=artma_${{ steps.getVersion.outputs.PACKAGE_VERSION }}.tar.gz" >> "$GITHUB_OUTPUT"
+
+      - name: Echo the metadata to console
+        run: |
+          echo "PACKAGE_VERSION=${{ steps.getVersion.outputs.PACKAGE_VERSION }}"
+          echo "TAG_NAME=${{ steps.getVersion.outputs.TAG_NAME }}"
+          echo "PKG_FILE_NAME=${{ steps.getPackageName.outputs.PKG_FILE_NAME }}"
+
+  submitToCran:
+    runs-on: ubuntu-latest
+    needs: determinePackageMetadata
     steps:
       - name: Check out repository
         uses: actions/checkout@v4
@@ -42,15 +88,10 @@ jobs:
           ./run.sh setup --no-box-check
         shell: bash
 
-      - name: Construct package local file name
-        id: constructPackageName
-        run: |
-          echo "PKG_FILE_NAME=artma_${{ inputs.PACKAGE_VERSION }}.tar.gz" >> "$GITHUB_OUTPUT"
-
       - name: Get release asset URL
         id: getReleaseUrl
         run: |
-          TAG="v${{ inputs.PACKAGE_VERSION }}"
+          TAG="${{ needs.determinePackageMetadata.outputs.TAG_NAME }}"
           REPO="${{ github.repository }}"
 
           ASSET_INFO=$(curl -s "https://api.github.com/repos/${REPO}/releases/tags/${TAG}")
@@ -71,7 +112,7 @@ jobs:
       - name: Submit to CRAN
         run: |
           source("./scripts/R/release.R")
-          built_path <- "${{ steps.constructPackageName.outputs.PKG_FILE_NAME }}"
+          built_path <- "${{ needs.determinePackageMetadata.outputs.PKG_FILE_NAME }}"
           print(paste("Submitting package:", built_path))
           submit_cran(pkg = ".", built_path = built_path, args = NULL)
         shell: Rscript {0}
